site_name: Simplified Practice API Documentation
nav:
    - Home: index.md
    - Tenancy Authentication: tenancy-auth.md
    - User Authentication: user-auth.md
    - Locations: locations.md
theme: readthedocs